######################################################################
# Automatically generated by qmake (3.0) Mon Aug 8 15:49:36 2016
######################################################################

TEMPLATE = app
TARGET = TypeIt
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += about_me.h result.h type_it.h
FORMS += about_me.ui result.ui type_it.ui
SOURCES += about_me.cpp main.cpp result.cpp type_it.cpp
RESOURCES += res/res.qrc
